POST http://localhost:8080/groupOfChickenChange/add
Content-Type: application/json

{ "historyDTO": {

},
  "groupOfChickenChangingDTO": {
    "chickenName": "Ali Chicken",
    "newGroup": 43,
    "dateOfChange": "2024-08-10"
  }

}
