POST http://localhost:8080/vaccinationOfOneChicken/addVaccinationGroup
Content-Type: application/json

{
  "GroupName": "gruppe1",
  "dateOfVaccination": "testToday",
  "timeOfVaccination": "testNow",
  "activeIngredient": "testIngredient",
  "crowdOfVaccination": "testCroud"
}