spring.datasource.url=jdbc:postgresql://localhost:5432/chicken_management
spring.datasource.username=postgres
spring.datasource.password=postgres2023
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

